SRC         = Heap_Program

# We never run small.out since it's not feasible.
TARGETS			= qc.out qcGen.out smart.out

all : $(TARGETS)

# Must come after all target.
include ../Config.mk


# %.pdf : $(TARGETS)
# 	gnuplot script.gnp

